# Site settings
title: Learn swift
email: coolhydr@gmail.com
description: "Swift blog"
baseurl: "www.coolhydro.github.com"
url: "http://www.coolhydro.github.com"
twitter_username: coolhydro
github_username:  coolhydro

# Build settings
markdown: kramdown
permalink: pretty
